### ISSUE TITLE
crash on parsing [Pseudomonas cichorii (Swingle 1925) Stapp 1928]

### ISSUE THREAD

**Issue by jhpoelen** [GlobalNamesArchitecture/gnparser#309]
When parsing ```Pseudomonas cichorii (Swingle 1925) Stapp 1928``` using

```scala
ScientificNameParser.instance
       .fromString(name)
      .canonized(showRanks = false)
      .getOrElse("")
```

for v0.3.2 on scala 2.11

the following stacktrace is reported:

tracktrace:

```


An exception or error caused a run to abort: scalaz.Scalaz$.ToOptionIdOps(Ljava/lang/Object;)Lscalaz/syntax/std/OptionIdOps; 
java.lang.NoSuchMethodError: scalaz.Scalaz$.ToOptionIdOps(Ljava/lang/Object;)Lscalaz/syntax/std/OptionIdOps;
	at org.globalnames.parser.AuthorsGroup.<init>(AST.scala:198)
	at org.globalnames.parser.Parser.authorsGroup(Parser.scala:505)
	at org.globalnames.parser.Parser.authorsYear(Parser.scala:496)
	at org.globalnames.parser.Parser.authorship1(Parser.scala:490)
	at org.globalnames.parser.Parser.basionymAuthorship1(Parser.scala:473)
	at org.globalnames.parser.Parser.basionymAuthorship(Parser.scala:469)
	at org.globalnames.parser.Parser.combinedAuthorship1(Parser.scala:436)
	at org.globalnames.parser.Parser.combinedAuthorship(Parser.scala:432)
	at org.globalnames.parser.Parser.authorship(Parser.scala:427)
	at org.globalnames.parser.Parser.species(Parser.scala:177)
	at org.globalnames.parser.Parser.name3(Parser.scala:144)
	at org.globalnames.parser.Parser.name(Parser.scala:119)
	at org.globalnames.parser.Parser.hybridFormula(Parser.scala:68)
	at org.globalnames.parser.Parser.sciName1(Parser.scala:58)
	at org.globalnames.parser.Parser.sciName(Parser.scala:23)
	at org.globalnames.parser.ScientificNameParser$$anonfun$1.apply(ScientificNameParser.scala:47)
	at org.globalnames.parser.ScientificNameParser$$anonfun$1.apply(ScientificNameParser.scala:47)
	at org.parboiled2.Parser.runRule$1(Parser.scala:143)
	at org.parboiled2.Parser.phase0_initialRun$1(Parser.scala:151)
	at org.parboiled2.Parser.__run(Parser.scala:204)
	at org.globalnames.parser.ScientificNameParser.fromString(ScientificNameParser.scala:47)
	at org.globalnames.parser.ScientificNameParser.fromString(ScientificNameParser.scala:35)
	at org.planteome.samara.ParserApsnet.canonize(ParserApsnet.scala:86)
```

**Comment by alexander-myltsev** [comment]
This is internal dependencies conflict. I checked: it works in upcoming `v0.3.3`.

**Comment by jhpoelen** [comment]
@alexander-myltsev thanks! hoping to give v0.3.3 a try whenever it is available.
