### ISSUE TITLE
Best practices for parsing a single name in native scripting language (daemon-mode?)

### ISSUE THREAD

**Issue by mjy** [GlobalNamesArchitecture/gnparser#323]
Assuming the biodiversity gem is for all intents and purposes deprecated (i.e. no longer tracking individual improvements realized here), and assuming I want to use native Ruby, what's the best practice for using gnparser?  

My use case is query processing, I get a *single* name string, break it down, and use the pieces to search against my index.  Spawning to the shell is possible, but the JVM is loaded every time, so this isn't a good solution.  Sending the query to a web endpoint would take too long.  It seems like what's missing is a daemon style approach?  Or, more than likely, I'm missing something.

It seems like this is an issue for all the native scripting languages (R, Python, etc) that can't/won't J-ify themselves for whatever reason.

**Comment by alexander-myltsev** [comment]
@mjy , did you consider using https://github.com/GlobalNamesArchitecture/gnparser#usage-as-a-socket-server ? It expects new-line delimited list of strings -- each string is a name to parse.

**Comment by mjy** [comment]
@alexander-myltsev Exploring that- currently not working, maybe my Java version?  I followed the wget instructions, and the `gnparse name "Homo sapiens"` worked, then:

`
matt@MacBook-Pro-71 Downloads$ gnparse socket --port 1234
Exception in thread "main" java.lang.UnsupportedClassVersionError: akka/actor/ExtensionId : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.globalnames.GnParser$.main(GnParser.scala:75)
	at org.globalnames.GnParser.main(GnParser.scala)
`

**Comment by alexander-myltsev** [comment]
Akka uses Java 8. Alas, you should update Java to use it.

**Comment by dimus** [comment]
Issue moved to [GlobalNamesArchitecture/biodiversity #14](https://github.com/GlobalNamesArchitecture/biodiversity/issues/14) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dimus** [comment]
Oups, it did not suppose to go to biodiversity, my bad. I added a line in documentation about using a 'socket' library for a specific language.
